### ISSUE TITLE
Add "Info" or "FAQ" button

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/web-mapping-dev#12]
Add another button icon on map to provide clearer information on the data and features

**Comment by roikle** [comment]
**Addition task requirements based on a recent meeting:**

* The Info Button should be linked to the existing content that opens when the `More Information` button at the top is clicked. 
* Note: The existing More Information button is using a font-awesome icon. Not sure if we will want a new asset for the bottom icon, or use this existing one, but the font-awesome icon is available, and could be adapted to use it's larger size.

**Comment by roikle** [comment]
Pull request #26 adds the help button which opens up the existing help window.

Another task which may need to happen is adding an item to the existing help window modal window, with text describing the new help button. Not sure if this is a required, but any text added will need to be translated.
