### ISSUE TITLE
Set maxBounds for map to the extent of Canada and update inital zoom.

### ISSUE THREAD

**Issue by roikle** [CSBP-CPSE/web-mapping-dev#20]
Tasks:
-  [x] Set maxBounds of map to the extent of Canada.
-  [x] Update default zoom level from 3 to 2, in order to prevent clipping of Canadian land masses on initial load for new users.

**Comment by roikle** [comment]
While digging into the code, I've learned a bit more about the initial bounds of LODE-Viewer.  

**Observations:**
* My initial assumption was that the initial bounds for the map was set to a global extent (i.e. showing the whole world). This is incorrect, the LODE-Viewer attempts to retrieve the previous centre of the map from the last time it was used from localStorage, and if it's not available uses the lat/long of 60.847/-105.3905, with an initial zoom of 3.
* There is also a home button on the map which will set the map bounds to the full extent of Canada when clicked.

**Recommendations:**
* Have the default zoom changed from **3**  to **2**, so that the initial map doesn't cut off portions of the country (note: this may vary based on a user's screen resolution, but zoom level 3 on my laptop (1600x900) definitely cuts off large sections of Canada). 
* The current approach to handling the initial loading bounds seems better then forcing a Canadian extent on the user (especially for frequent users). So I recommend updating the issue to only focus on updating the default zoom level, and leaving how the map extent is set.

**Comment by Noznoc** [comment]
Can you note set bound (e.g., maxBounds) and cache lat/long for frequent users?

**Comment by Noznoc** [comment]
https://docs.mapbox.com/mapbox-gl-js/api/map/

Can use `.maxBounds` and `.hash`

**Comment by roikle** [comment]
> Can you not set bound (e.g., maxBounds) and cache lat/long for frequent users?

Setting a maxBounds sounds like a great idea! I'm assuming an extent that encompasses the entire Canadian landmass would be sufficient?

**Comment by Noznoc** [comment]
[-142.0, 41.0, -52.0, 83.0]
