### ISSUE TITLE
Add Tool Tip/Pop-Ups for Abbreviations in Text

### ISSUE THREAD

**Issue by roikle** [CSBP-CPSE/web-mapping-dev#36]
**Issue:** Sometimes abbreviations/jargon are used in the text. To help improve clarity of the information, we should enhance the content to display an information pop-up when a user hovers over a specific piece of text.

See https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2018015-eng.htm for an example of how this is currently being preformed on a Statistics Canada website.

**Comment by Noznoc** [comment]
I think we should also include this for the "Skip the interactive features and go directly to the data table.
Note: Census subdivision (CSD) is the general term for municipalities (as determined by provincial/territorial legislation) or areas treated as municipal equivalents for statistical purposes (e.g., Indian reserves, Indian settlements and unorganized territories)." when hovering over "Enter municipality/**CSD** name or ID:"

**Comment by Noznoc** [comment]
Check out a first go at it: https://github.com/CSBP-CPSE/web-mapping-dev/commit/7f75e86ac2d67a3727a06800b8e495a9aac7a96d

**Comment by Noznoc** [comment]
@msmailes please review the following French text for LODE Viewer intro. Thanks! Note: the tooltip in the French image appears when you hover over the SDR (same in English version when hovering over CSD).

English:
![image](https://user-images.githubusercontent.com/19412148/103679465-dbe40b00-4f52-11eb-8beb-a5b91bac37ae.png)

French:
![image](https://user-images.githubusercontent.com/19412148/103679560-f61de900-4f52-11eb-81e3-8a3226d96845.png)

**Comment by Noznoc** [comment]
@msmailes also this text as well:
French:
![image](https://user-images.githubusercontent.com/19412148/103679713-31b8b300-4f53-11eb-91b2-974372c73b11.png)

English:
![image](https://user-images.githubusercontent.com/19412148/103679747-3c734800-4f53-11eb-81e3-8f8788013063.png)

**Comment by msmailes** [comment]
@Noznoc Changes to the first set of images in the Legend:

Les Empreintes d'Immeubles -> Empreintes d'immeubles
Opacité de l'empreinte des bâtiments -> Opacité de l'empreinte d'immeuble

**Comment by msmailes** [comment]
Changes to the second set of images, text below the map:

1. Remove "La" in front of BDOI title to maintain consistency.

2. Shorten first sentence of BDOI to: Une collection de données ouvertes sur les immeubles, en particulier les empreintes d'immeubles.

**Comment by roikle** [comment]
Thank you for the French translations, I'll make sure to add the changes.

**Comment by Noznoc** [comment]
OK great, and thank you @roikle, was going to do it this afternoon, but feel free to do it if you want. Let me know if you're busy though, can do it
