### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by Noznoc** [CSBP-CPSE/web-mapping-dev#39]
@roikle can you update OpenStreetMap to: '© OpenStreetMap contributors' and `© Contributeurs d'OpenStreetMap` for the english and french legend plz?

**Comment by roikle** [comment]
Submitted update to feature-add-building-footprints branch in commit d92c11a2c3c5f62784516480f1e40594a1526fc4

**Comment by Noznoc** [comment]
Looks good, thanks
