### ISSUE TITLE
table.py output splits data into json files but the data contained in the files is csv

### ISSUE THREAD

**Issue by roikle** [CSBP-CPSE/web-mapping-dev#4]
When input csv table data is processed by the table.py script, the data is split by Census Subdivisions. The output of this splitting of data is a series of json files but the content inside the json files csv.

I wondering if this script should be updated, so that the output file type is csv, to reflect the content of the files.

**Comment by Noznoc** [comment]
Hi Rob, there is a reason for this. I'll send you an email tmrw explaining why.
